### ISSUE TITLE
Chrono library has updated and the installation does not work

### ISSUE THREAD

**Issue by LeonYang5114** [amelmquist/Chrono_Gazebo#4]
[This commit](https://github.com/projectchrono/chrono/commit/2c21f348bc36a6809f48cacfe252a5aac26ff9c5#diff-25d902c24283ab8cfbac54dfa101ad31) in chrono make some changes to the chrono_vehicle directory, so that
```
#include "chrono_vehicle/vehicle/Vehicle.h
```
does not work any more.
It seems that [here](https://github.com/amelmquist/Chrono_Gazebo/blob/master/gazonoVehicle/gazonoVehicle.cc#L22), [here](https://github.com/amelmquist/Chrono_Gazebo/blob/master/gazonoVehicle/gazonoVehicle.cc#L25), and [here](https://github.com/amelmquist/Chrono_Gazebo/blob/master/gazonoVehicle/purePursuitDriver.cc#L9) need to be modified.

**Comment by amelmquist** [comment]
This issue has been fixed and pushed
